[package]
name = "six"
version = "0.1.0"
authors = ["Chase <cjopsahl99@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
undup = "0.0.1"
itertools = "0.9.0"
